### ISSUE TITLE
Implement selenium grid with actions

### ISSUE THREAD

**Issue by worming004** [reqnroll/Reqnroll.Actions#1]
For now, selenium integration work well for browser.

We are willing to use reqnroll with selenium grid. From what I understand, there is no implementation of it.

Are you open for pull request about it ?

**Comment by gasparnagy** [comment]
@worming004 My understanding was that the implementation is (should not be) bound to any concrete browser, so in principle it should also work with selenium grid. 

Could you please confirm that is not working in a way that it is shown in this [general](https://github.com/reqnroll/Reqnroll.Actions/blob/main/Plugins/Reqnroll.Actions.Selenium/Reqnroll.Actions.Selenium.IntegrationTests/reqnroll.actions.json) and this [browser specific](https://github.com/reqnroll/Reqnroll.Actions/blob/main/Plugins/Reqnroll.Actions.Selenium/Reqnroll.Actions.Selenium.IntegrationTests/reqnroll.actions.chrome.json) config?

If there is any change needed for the grid, the PR is welcome, for sure.

**Comment by worming004** [comment]
I still didn't try it since I've opened the PR. I'll comment here if my team is willing to try

**Comment by gasparnagy** [comment]
No prob. I close this issue for now. Feel free to reopen if you or the team discovers anything.

**Comment by DomZZ** [comment]
Hello @worming004, I am also very interested to have support for selenium grid and how to achieve this.
Thanks a lot
